<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TankSwarmCode.Arena\TankSwarmCode.Arena.csproj" />
    <ProjectReference Include="..\TankSwarmCode.SwarmTank\TankSwarmCode.SwarmTank.csproj" />
<ProjectReference Include="..\TankSwarmCode.SwarmTanks.Red\TankSwarmCode.SwarmTanks.Red.csproj" />
    <ProjectReference Include="..\TankSwarmCode.SwarmTanks.Blue\TankSwarmCode.SwarmTanks.Blue.csproj" />
  </ItemGroup>


  <Target Name="PublishSingleFileOnReleaseBuild" AfterTargets="Build"
          Condition="'$(Configuration)' == 'Release' AND '$(PublishSingleFile)' != 'true'">
    <Exec Command="dotnet publish &quot;$(MSBuildProjectFullPath)&quot; /p:PublishProfile=SingleFileWin64 /p:RuntimeIdentifier=win-x64" />
  </Target>

</Project>